### ISSUE TITLE
How can I show time as HH:MM format?

### ISSUE THREAD

**Issue by yu-coder** [Shopify/polaris-react#2487]
Hi, I am showing time using **TextField** component in **React Polaris**.

`<TextField type="time" label="Time" value="13:25" onChange={this.onChangeTime)} />`

Currently, it shows as **01:25:00 PM**.

Is there any way to show only **HH:MM** format?

**Comment by yu-coder** [comment]
I have fixed adding `step="0"`

`<TextField type="time" label="Time" step="0" value="13:25" onChange={this.onChangeTime)} />
`

**Comment by mckrava** [comment]
I still have the same issue https://github.com/Shopify/polaris-react/issues/4873 but `step="0"` doesn't help (((
