### ISSUE TITLE
DataTable row heights do not recalculate when row content changes

### ISSUE THREAD

**Issue by andrewpye** [Shopify/polaris-react#387]
# Issue summary
If the data backing a `DataTable` changes, the table updates to display the new content, but the row heights don't recalculate resulting in issues like this:

![data-table-row-height](https://user-images.githubusercontent.com/5737342/43464714-76b4ee00-94e4-11e8-8c1c-878d097317fd.gif)

The code for the above GIF is [here](https://codesandbox.io/s/189y72pl2j) - when the button is pressed, the first row's title is made significantly longer, the third row's title is made shorter, and a new row is pushed into the table.

## Expected behavior
Row heights update when table content changes.

## Actual behavior
Row heights do not update when table content changes, potentially leaving rows too tall/short for their content.

## Steps to reproduce the problem
Update the `rows` array backing the `DataTable`.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 2.5.0
- Browser: Chrome Version 67.0.3396.99 (Official Build) (64-bit)
- Device: MacBook Pro
- Operating System: macOS Sierra Version 10.12.6 (16G29)

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 We _are_ accepting issue reports and feature requests<br />
🌟 Feature requests that we can’t get to right away will be closed. However, we track all requests and will use it to set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by ry5n** [comment]
Thanks @andrewpye. On it!

**Comment by silvainSayduck** [comment]
FYI, another example of this behavior can be seen here: https://codesandbox.io/s/32v3llnjv1.

Just add some new lines to the `TextField`, and see that the first column's cell doesn't get its height recomputed.

**Comment by Nisthar** [comment]
@ry5n are there any workaround for this? 

I am building a shopify app and it really needed this feature. Don't want to to use a custom table component.

**Comment by solonaarmstrong** [comment]
This has been fixed and will be in our next release.

**Comment by gerwinbrunner** [comment]
This seems to still not work in v 3.4.0 
@solonaarmstrong which release did you refer to?

**Comment by solonaarmstrong** [comment]
This is from the latest release 3.4.0. (Sorry, the video recording is too big to upload. This screenshot is taken after pressing the button from the original issue).

![screen shot 2019-01-09 at 3 01 10 pm](https://user-images.githubusercontent.com/6239480/50935028-70c4d400-141f-11e9-8b8c-3cab841d3c2f.jpg)

Are you able to provide something to reproduce the trouble you're running into, @gerwinbrunner ?

**Comment by arieljaw12** [comment]
Hello @solonaarmstrong 

I'm using version 3.4 but I think I'm having the same issue. See this images:
![image](https://user-images.githubusercontent.com/32110225/50968461-e8dfd800-14b9-11e9-92b1-f9e3260f7840.png)

And when you click the last button that has a `Collapsible` with a `TextContainer` is even worst:
![image](https://user-images.githubusercontent.com/32110225/50968496-0745d380-14ba-11e9-97c5-4d7cb8da1eb8.png)


I'm not sure if it is the same issue or if I'm not usign `DataTable` component correctly. The column types are (from left to right)
* Polaris `<Link>` component.
* String
* String
* More complex component, but basically is:
```
     <Stack vertical>
        <Button>
          Retailers
        </Button>
        <Collapsible>
          <TextContainer>
            ...
          </TextContainer>
        </Collapsible>
      </Stack>
```

I will be grateful if you can help me :)

Regards,
Ariel

PS: I also try to put the column with long height first and I got this result:
![image](https://user-images.githubusercontent.com/32110225/50971616-3280f080-14c3-11e9-895b-9cab349268d8.png)

**Comment by solonaarmstrong** [comment]
@arieljaw12 I'm not able to reproduce the problem. Would you be able to create a reduced test case with the code you're using? Thank you.

**Comment by fchienvuhoang** [comment]
![screen shot 2019-01-22 at 4 44 43 pm](https://user-images.githubusercontent.com/4451749/51526554-3dddff80-1e65-11e9-95e6-922a2acd7fd9.png)
anyone got this bug css like me?

**Comment by solonaarmstrong** [comment]
@fchienvuhoang Interesting. I've created a separate issue. https://github.com/Shopify/polaris-react/issues/913

**Comment by arieljaw12** [comment]
> @arieljaw12 I'm not able to reproduce the problem. I'm wondering what you're using as your `columnContentTypes` for the link and stack components? It only accepts `text` or `numeric`. Would you be able to create a reduced test case with the code you're using? Thank you.

Hello @solonaarmstrong 

I'm using `text` for both, the `Link` and the `Stack` component. I create an example of my code with harcoded data, you can see here: https://codesandbox.io/s/kkrr9z275r

As you see I'm experimenting the same issue when I give the table more screen width:
![image](https://user-images.githubusercontent.com/32110225/51612269-de80fd80-1eff-11e9-8832-9d1b11fc198f.png)

You can see that the highlighted row get different row's height at the `Link` column

Regards,
Ariel

**Comment by solonaarmstrong** [comment]
@arieljaw12 The screenshot you have there is not what renders in the sandbox. The row borders don't render, so something's breaking. I was able to strip it down and recreate it locally. One thing stands out:

```
headings={[
          <Heading>Order</Heading>,
          <Heading>Total price</Heading>,
          <Heading>Split total</Heading>,
          <Heading>Retailers</Heading>
        ]}
```

The headings are typed as an array of strings `string[]`.

Moving forward we've talked about making data table more flexible so it can accept headings and row links, but I don't have a clear timeline on what that will happen.

**Comment by dpersing** [comment]
Dropped a question about the heading hierarchy in the related style guide PR: https://github.com/Shopify/polaris-styleguide/pull/2493#issuecomment-456935369

Currently, the Accessibility heading is getting rendered as an `<h3>`, which is throwing off the section hierarchy.

**Comment by arieljaw12** [comment]
@solonaarmstrong Hello, thanks for the reply and your time. I think that you have to resize the screen on sandbox to see the row highlighted. With the default size the highlight is not rendered. I replaced the `Heading` components with plain `strings` but I'm still get the same:

![image](https://user-images.githubusercontent.com/32110225/51677566-d5a03280-1fb8-11e9-9d5e-3bc6b3f260c6.png)


See that my screen is larger than the default. Maybe the in the image you can not appreciate the row highlighted because its quality (it's light gray).

Regards,
Ariel
