### ISSUE TITLE
Popover with Action List displacing extra height (seen in Polaris v 2.8.0)

### ISSUE THREAD

**Issue by djirdehh** [Shopify/polaris-react#433]
# Issue summary

As part of updating the `partners` repo to Polaris v2.8, we've noticed some Popovers induce extra height only when the text in an ActionList within has spacing characters.

![polaris_react](https://user-images.githubusercontent.com/12476938/45902148-9caa4400-bdb3-11e8-8057-f0788873d002.gif)

Relevant discussion: https://github.com/Shopify/partners/pull/11963#pullrequestreview-157747839

cc @solonaarmstrong 

## Code that was used

```
state = {
  showPopover: true,
  preventAutofocus: true,
};

togglePopover() {
  this.setState(({showPopover}) => {
    return {
      showPopover: !showPopover,
      preventAutofocus: showPopover,
    };
  });
}

onCloseHandler() {
  return null;
}

render() {
  // ...

  <Popover
    active={showPopover}
    onClose={this.onCloseHandler}
    preferredPosition="below"
    preventAutofocus={preventAutofocus}
    activator={
      <Button onClick={this.togglePopover} plain>
        <span className="admin-links-preview__popover-activator">
          More actions
          <Icon source="caretDown" />
        </span>
      </Button>
    }
  >
    <ActionList
       items={[
         {
           content: 'Share on Facebook'
         }
      ]}
     />
  </Popover>
  
  //...
}
```
## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: v.2.8
- Browser: Chrome
- Device: Mac
- Operating System: High Sierra (10.13.5)

---

**Comment by solonaarmstrong** [comment]
We just released 3.0 and hopefully it's been resolved with the update.

**Comment by djirdehh** [comment]
Yup definitely. Will close this for now!

**Comment by GuptaAman08** [comment]
Hi @djirdehh ,

I am still facing this issue when i use shopify polaris Popover component in one of my app. Can you help me in any way.
`  <Stack> <Stack.Item>
       <Popover active={active} activator={bulkActionButtonActivator} onClose={toggleActive}>
                <ActionList
                  items={bulkAction}
                />
              </Popover>
            </Stack.Item>  
          </Stack>`



<img width="621" alt="Screenshot 2021-02-13 at 6 02 28 PM" src="https://user-images.githubusercontent.com/31820923/107850071-b4bc0b80-6e25-11eb-8f16-205b9c6d5ee7.png">
